kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: opa-mutating-webhook
webhooks:
  - name: opa.opa.svc
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["services"]
    clientConfig:
      service:
        namespace: opa
        name: opa
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXdOVEE0TVRZME9Wb1hEVE15TVRBd01qQTRNVFkwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUlpClFDR2NEc3k2NTNxK1BSeTdrSTJhV1ZZRGxqclFRU3l4NExiZ1NMNUpQaTRtZElSTUttL1NqYU9zWUhVWk9EYmMKTFozQUc0NGNpazR5SGNaUm9kdi9WaVJyNHJCNDhEVFl0dEVveUVSYXlmejhjS3BuU1VSOUtKbkg4NTdaSXVCRQp2Qmp0M3lmWnQxNWRiWFQ5QmJzdS9OWEJmWVVvWktyYlhuR1ZPSWEweVpSNUxLZGlEdGNncFp1bm5OQ01OVzdUCnBYMkZIYktIblRFSi9HTDdtaUkybGh5RVUrR0lYbnlnbDVvbUVsY1R0Vlp0V09jYVlTd2tBZnE1U3ZENVpGRW0KczNrTXFNKy84QUxRYkhJZWxueXd2VTVmQjJOMUFVYVNYMmdNY3g2MDVaNVlNd0NRNFlGZFJlbzhkOVZUMDhnLwpVWS9UOHg4YUwxS3FWc2U5N0prQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIT1dGaysveVZnTG0yazFTVWpTakZVemYvc1VNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR1hVZmgwUFRvUU9CNzVlTlFKZwphRGk4b1c1MjhlVzRMSC9rS0V6UGRTVUNYZklZaVdWQjArOGxaOWJDcWRxVXp5a3VoVlY3Nng1UE1VRmtzSk44Ckhpd3RZdkk5TXYzbFlBTURnbElFZElQQXBGMldlZTNseWNQVEJleU03akg3OXp5MXdoMXFwTDNvbnJ0VWRicFcKaWRMQmVaWWlHdnIweitManJYVXBWV0JBNGNXWXkwcXhuUU90OHhvMHA2WHhlaUVTSDR5SzlMYUtyMkIxcm1odApEWWs3alFhaFVtdTRuU0lkTEY1YTRWUDZNcWV4UUVqN3R4WDVxNVl6RC9OblEzaTh3ZEQzdWxweXlZZUZqdlA5Cm5qNG9lNXJLMml5N3BSeHBmNzRMUE1jMzJuL0RRT0lybG05MUJOUTZadWZYWnBXTmV3VFpEZjVPUWFRTWNwQksKc2xzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    sideEffects: None
    admissionReviewVersions: ["v1"]
